// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyImport(arg1, arg2) {
  return window['go']['main']['App']['ApplyImport'](arg1, arg2);
}

export function CloudApplyDownloaded(arg1) {
  return window['go']['main']['App']['CloudApplyDownloaded'](arg1);
}

export function CloudAuthGetVcode() {
  return window['go']['main']['App']['CloudAuthGetVcode']();
}

export function CloudAuthLogin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloudAuthLogin'](arg1, arg2, arg3, arg4);
}

export function CloudAuthLogout() {
  return window['go']['main']['App']['CloudAuthLogout']();
}

export function CloudAuthRegister(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CloudAuthRegister'](arg1, arg2, arg3, arg4, arg5);
}

export function CloudAuthStatus() {
  return window['go']['main']['App']['CloudAuthStatus']();
}

export function CloudAutoSyncDismiss() {
  return window['go']['main']['App']['CloudAutoSyncDismiss']();
}

export function CloudAutoSyncIgnore() {
  return window['go']['main']['App']['CloudAutoSyncIgnore']();
}

export function CloudAutoSyncRetry(arg1) {
  return window['go']['main']['App']['CloudAutoSyncRetry'](arg1);
}

export function CloudDownloadConfig(arg1, arg2) {
  return window['go']['main']['App']['CloudDownloadConfig'](arg1, arg2);
}

export function CloudListVersions() {
  return window['go']['main']['App']['CloudListVersions']();
}

export function CloudUploadConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['CloudUploadConfig'](arg1, arg2, arg3);
}

export function ConnectSSH(arg1) {
  return window['go']['main']['App']['ConnectSSH'](arg1);
}

export function DeleteQuickCommand(arg1) {
  return window['go']['main']['App']['DeleteQuickCommand'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DuplicateSSH(arg1) {
  return window['go']['main']['App']['DuplicateSSH'](arg1);
}

export function DuplicateSavedSession(arg1) {
  return window['go']['main']['App']['DuplicateSavedSession'](arg1);
}

export function ExportData() {
  return window['go']['main']['App']['ExportData']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportData() {
  return window['go']['main']['App']['ImportData']();
}

export function ImportDataWithPassword(arg1, arg2) {
  return window['go']['main']['App']['ImportDataWithPassword'](arg1, arg2);
}

export function ListQuickCommands() {
  return window['go']['main']['App']['ListQuickCommands']();
}

export function ListSavedSessions() {
  return window['go']['main']['App']['ListSavedSessions']();
}

export function PickFile() {
  return window['go']['main']['App']['PickFile']();
}

export function PickSavePath(arg1) {
  return window['go']['main']['App']['PickSavePath'](arg1);
}

export function ReorderQuickCommands(arg1) {
  return window['go']['main']['App']['ReorderQuickCommands'](arg1);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2, arg3);
}

export function SFTPList(arg1, arg2) {
  return window['go']['main']['App']['SFTPList'](arg1, arg2);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUpload(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUpload'](arg1, arg2, arg3);
}

export function SSHSendData(arg1, arg2) {
  return window['go']['main']['App']['SSHSendData'](arg1, arg2);
}

export function SSHSessionResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SSHSessionResize'](arg1, arg2, arg3);
}

export function SaveQuickCommand(arg1) {
  return window['go']['main']['App']['SaveQuickCommand'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['main']['App']['SaveSession'](arg1);
}

export function SessionStats(arg1) {
  return window['go']['main']['App']['SessionStats'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function TrustHostKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrustHostKey'](arg1, arg2, arg3);
}

export function VaultChangePassword(arg1, arg2) {
  return window['go']['main']['App']['VaultChangePassword'](arg1, arg2);
}

export function VaultDisablePassword(arg1) {
  return window['go']['main']['App']['VaultDisablePassword'](arg1);
}

export function VaultLock() {
  return window['go']['main']['App']['VaultLock']();
}

export function VaultSetPassword(arg1) {
  return window['go']['main']['App']['VaultSetPassword'](arg1);
}

export function VaultStatus() {
  return window['go']['main']['App']['VaultStatus']();
}

export function VaultUnlock(arg1) {
  return window['go']['main']['App']['VaultUnlock'](arg1);
}
