// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';
import {sshclient} from '../models';

export function ApplyImport(arg1:Array<store.Session>,arg2:Array<store.QuickCommand>):Promise<Record<string, any>>;

export function CloudApplyDownloaded(arg1:store.CloudPayload):Promise<Record<string, any>>;

export function CloudAuthGetVcode():Promise<Record<string, any>>;

export function CloudAuthLogin(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CloudAuthLogout():Promise<void>;

export function CloudAuthRegister(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CloudAuthStatus():Promise<Record<string, any>>;

export function CloudAutoSyncDismiss():Promise<Record<string, any>>;

export function CloudAutoSyncIgnore():Promise<Record<string, any>>;

export function CloudAutoSyncRetry(arg1:string):Promise<Record<string, any>>;

export function CloudDownloadConfig(arg1:number,arg2:string):Promise<Record<string, any>>;

export function CloudListVersions():Promise<Record<string, any>>;

export function CloudUploadConfig(arg1:string,arg2:boolean,arg3:boolean):Promise<Record<string, any>>;

export function ConnectSSH(arg1:main.ConnectRequest):Promise<main.ConnectResult>;

export function DeleteQuickCommand(arg1:number):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DuplicateSSH(arg1:string):Promise<main.ConnectResult>;

export function DuplicateSavedSession(arg1:number):Promise<store.Session>;

export function ExportData():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function ImportData():Promise<Record<string, any>>;

export function ImportDataWithPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ListQuickCommands():Promise<Array<store.QuickCommand>>;

export function ListSavedSessions():Promise<Array<store.Session>>;

export function PickFile():Promise<string>;

export function PickSavePath(arg1:string):Promise<string>;

export function ReorderQuickCommands(arg1:Array<number>):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPList(arg1:string,arg2:string):Promise<main.SFTPListResult>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUpload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SSHSendData(arg1:string,arg2:string):Promise<void>;

export function SSHSessionResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveQuickCommand(arg1:store.QuickCommand):Promise<store.QuickCommand>;

export function SaveSession(arg1:store.Session):Promise<store.Session>;

export function SessionStats(arg1:string):Promise<sshclient.Stats>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function TrustHostKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function VaultChangePassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function VaultDisablePassword(arg1:string):Promise<Record<string, any>>;

export function VaultLock():Promise<Record<string, any>>;

export function VaultSetPassword(arg1:string):Promise<Record<string, any>>;

export function VaultStatus():Promise<Record<string, any>>;

export function VaultUnlock(arg1:string):Promise<Record<string, any>>;
